// <auto-generated />
using Luyen_code_first_1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luyen_code_first_1.Migrations
{
    [DbContext(typeof(LuyencodefirstContext))]
    partial class LuyencodefirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Luyen_code_first_1.Models.NdcLoai_San_Pham", b =>
                {
                    b.Property<long>("ndcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ndcId"));

                    b.Property<string>("ndcMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ndcTenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ndcTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ndcId");

                    b.ToTable("NdcLoai_San_Pham");
                });

            modelBuilder.Entity("Luyen_code_first_1.Models.NdcSan_Pham", b =>
                {
                    b.Property<long>("ndcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ndcId"));

                    b.Property<decimal>("ndcDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ndcHinhAnh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ndcMaLoai")
                        .HasColumnType("bigint");

                    b.Property<string>("ndcMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ndcSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ndcTenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ndcTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ndcId");

                    b.HasIndex("ndcMaLoai");

                    b.ToTable("NdcSan_Pham");
                });

            modelBuilder.Entity("Luyen_code_first_1.Models.NdcSan_Pham", b =>
                {
                    b.HasOne("Luyen_code_first_1.Models.NdcLoai_San_Pham", "ndcLoai_San_Pham")
                        .WithMany("ndcSan_Phams")
                        .HasForeignKey("ndcMaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ndcLoai_San_Pham");
                });

            modelBuilder.Entity("Luyen_code_first_1.Models.NdcLoai_San_Pham", b =>
                {
                    b.Navigation("ndcSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
