// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TH_code_first.Models;

#nullable disable

namespace TH_code_first.Migrations
{
    [DbContext(typeof(TH_code_firstContext))]
    partial class TH_code_firstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TH_code_first.Models.NdcLoai_San_Pham", b =>
                {
                    b.Property<int>("ndcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ndcID"));

                    b.Property<string>("ndcMaLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ndcTenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ndcTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ndcID");

                    b.ToTable("ndcLoai_San_Phams");
                });

            modelBuilder.Entity("TH_code_first.Models.NdcSan_Pham", b =>
                {
                    b.Property<int>("ndcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ndcID"));

                    b.Property<decimal>("ndcDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ndcHinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ndcMaLoai")
                        .HasColumnType("int");

                    b.Property<string>("ndcMaSanPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ndcSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ndcTenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ndcTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ndcID");

                    b.HasIndex("ndcMaLoai");

                    b.ToTable("ndcSan_Phams");
                });

            modelBuilder.Entity("TH_code_first.Models.NdcSan_Pham", b =>
                {
                    b.HasOne("TH_code_first.Models.NdcLoai_San_Pham", "ndcLoai_San_Pham")
                        .WithMany("ndcSanPhams")
                        .HasForeignKey("ndcMaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ndcLoai_San_Pham");
                });

            modelBuilder.Entity("TH_code_first.Models.NdcLoai_San_Pham", b =>
                {
                    b.Navigation("ndcSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
